# Generated by Django 4.1.1 on 2022-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="files",
                        verbose_name="archivo adjunto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "comentario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="files",
                        verbose_name="archivo adjunto",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (None, "---------"),
                            ("PRENSA", "Prensa y Redacción"),
                            ("AUDIOVISUAL", "Audiovisual"),
                            ("DISENHO", "Diseño Grafico"),
                            ("WEB", "Web"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Pendiente"),
                            (2, "En curso"),
                            (3, "Finalizado"),
                            (4, "Rechazado"),
                        ],
                        default=1,
                        verbose_name="estado",
                    ),
                ),
                (
                    "urgency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Urgente"),
                            (2, "Alta"),
                            (3, "Media"),
                            (4, "Baja"),
                        ],
                        default=3,
                        verbose_name="urgencia",
                    ),
                ),
                (
                    "rejection_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="motivo del rechazo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="último cambio"),
                ),
                (
                    "sub_category",
                    models.CharField(
                        max_length=5000, null=True, verbose_name="subcategoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "ordering": ["-created_at"],
            },
        ),
    ]
