# Generated by Django 4.1.1 on 2022-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_url_path_notification_url_args_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status_red',
            field=models.CharField(default='NO_READ', max_length=50),
        ),
    ]
